pyenphase/pyenphase

- src/pyenphase/models/dry_contacts.py
- src/pyenphase/models/encharge.py
The Encharge and Dry Contacts models have properties that come from 2 different API endpoints. This adds comments to specify a primary API endpoint that returns the majority of the data, and comments to specify which properties come from other API endpoints. Referenced everything by their constant name in const.py
> chore: Add comments for properties that come from additional API endpoints

- .github/workflows/ci.yml
Require Python 3.11 as the minimum version
> refactor!: drop python3.10 support

- src/pyenphase/auth.py
- src/pyenphase/const.py
- src/pyenphase/envoy.py
- src/pyenphase/firmware.py
If the internet connection is flakey, or offline even though we had a token, envoy setup would still timeout
We need a long read timeout for it to work as its apparently resolving the incoming host that is making the http connection
Worse then its having trouble with dns, its going to redirect to `https://localhost` 🤦 
```
HTTP/1.1 301 Moved Permanently
Server: openresty/1.17.8.1
Date: Tue, 08 Aug 2023 19:32:50 GMT
Content-Type: text/html
Content-Length: 175
Connection: close
Location: https://localhost/
```
> fix: adjust timeouts for when envoy is having trouble with DNS

- src/pyenphase/envoy.py
Sometimes the production endpoint will return bad json and we need to try again. We should not retry when probing since that will give us wrong results.
Split the request function into one that retries on bad json and one that does not for probing
fixes
```
2023-08-08 10:34:10.393 ERROR (MainThread) [homeassistant.components.enphase_envoy.coordinator] Unexpected error fetching Envoy 121729017746 data: unexpected character: line 1 column 1 (char 0)
Traceback (most recent call last):
File "/Users/bdraco/home-assistant/homeassistant/helpers/update_coordinator.py", line 293, in _async_refresh
self.data = await self._async_update_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/bdraco/home-assistant/homeassistant/components/enphase_envoy/coordinator.py", line 151, in _async_update_data …
```
> fix: handle envoy sending bad json

- src/pyenphase/updaters/api_v1_production_inverters.py
There is only one endpoint for inverters, no need to check
> fix: remove unreachable code in inverters updater

- src/pyenphase/envoy.py
- tests/test_endpoints.py
Adds tests to make sure the register interface works as expected
Adds an example to the tests on how one might register a new updater to scape older firmware since this library is ADR004 compliant and does not support webscraping
> feat: refactor register interface to allow unregistering an updater

- src/pyenphase/models/dry_contacts.py
The `grid_action`, `micro_grid_action`, and `gen_action` fields in `/ivp/ss/dry_contact_settings` can also return `schedule` as a value
`schedule` means the relay/load will be active between `essential_start_time` and `essential_end_time`
> fix: add "schedule" to DryContactAction

- src/pyenphase/envoy.py
- src/pyenphase/models/dry_contacts.py
- tests/test_endpoints.py
Adds a function to change settings for the Enpower dry contacts / load shedding relays.
takeaways from reverse engineering this:
- The entire settings object for the relay you're changing has to be sent in the POST request or else the Envoy might crash
- Boolean values have to be sent as lowercase strings in the POST (or you'll get a HTTP 500 error saying the field is missing
> feat: add support for changing settings on dry contact relays

- src/pyenphase/firmware.py
The retry was too broad and too frequent. We should instead raise and let HA retry so startup can proceed
> fix: startup was blocked for multiple minutes if the envoy was offline

- src/pyenphase/envoy.py
- tests/test_endpoints.py
The envoy will return the old state of the relay for a number of seconds after changing the state. This PR updates our open/close functions to preemptively update the state we're storing in the EnvoyData which helps with programs like Home Assistant where the switch would toggle back and forth due to the previous state being returned.
> fix: preemptively update dry contact state when toggling

- devtools/fixture_collector.py
As first step for #69, add ivp/meters and ivp/meters/readings to fixture collector.
Be aware result are (probably) more configuration dependent than firmware dependent. These pages only apply to IQ Gateway/Envoy metered with both Production and Consumption CT installed and configured.  ivp/meters where report 'split phase' or '3 phase' based on actual configuration and net-consumption or total-consumption based on the position of the consumption CT. This implies that within same firmware there is multiple datasets coming back.
> feat: add ivp/meters and ivp/meters/readings to fixture collector

- src/pyenphase/updaters/production.py
- tests/test_endpoints.py
* 3.9.36 with correct password
- `/production` = 401
- `/production.json` = 200, good data
> fix: handle /production returning a 401 even with the correct auth on some 3.x firmwares

- src/pyenphase/__init__.py
- src/pyenphase/const.py
- src/pyenphase/envoy.py
- src/pyenphase/models/envoy.py
- src/pyenphase/models/tariff.py
- src/pyenphase/updaters/tariff.py
- tests/__snapshots__/test_endpoints.ambr
- tests/test_endpoints.py
Adds initial models for tariff data from `/admin/lib/tariff` and adds functions to enable and disable charging the Enphase batteries from grid power.
Unlike other API endpoints, the `/admin/lib/tariff` endpoint requires an HTTP PUT instead of an HTTP POST
Still need to update tests.
> feat: Add initial tariff support and charge from grid functions

- src/pyenphase/envoy.py
- tests/test_endpoints.py
Add support for changing battery storage mode and setting the reserve state-of-charge.
Current known options for the storage mode are in `models.tariff.EnvoyStorageMode`
Backup = full backup
Self Consumption = battery will discharge to the reserve SoC and then pull from grid
Savings Mode = My understanding is this uses the schedule set in Enlighten to pull from the battery during times when energy cost is higher and uses the grid when costs are lower.
For reserve SoC the API seems to want a float, but when making changes from Enlighten and then querying the API I've never seen a decimal besides `.0` - so I set the function up to accept integers and then convert that to a rounded float.
> feat: Add support for changing storage mode and reserve soc

- src/pyenphase/models/tariff.py
- tests/test_endpoints.py
Some firmware versions don't return a `date` for storage_settings in `/admin/lib/tariff`
fix for https://github.com/home-assistant/core/issues/103448
> fix: Make date field optional in storage settings tariff model

- src/pyenphase/updaters/base.py
Pylance reports parameter data in updaters update method as different from base class EnvoyUpdater.
As all updaters use envoy_data, renaming the one in base to envoy_data as well.
> refactor: rename data parameter of EnvoyUpdater base class to envoy_data

- src/pyenphase/models/common.py
- src/pyenphase/models/envoy.py
- tests/__snapshots__/test_endpoints.ambr
- tests/test_endpoints.py
Add production and consumption records for phases to envoy data model.
Extend common properties with phase setup information.
Add tests for empty data structures added.
Update snapshot with empty data structures for production and consumption phases.
New structures are not used yet, they all contain their default values.
> refactor: add empty data structures and tests for phase information

- .readthedocs.yml
Switch to python 3.11 for readthedocs as pyenphase code uses StrEnum which causes build on 3.10 to fail
> chore: Bump python for readthedocs to 3.11

- src/pyenphase/envoy.py
- tests/test_endpoints.py
Currently pyenphase only logs debug messages for a send request, the reply is not logged in debug. During probe little is written to the debug log and when issues occur in most cases only secondary information can be used to determine what is going on. During update cycle scope is limited to what was found during probe.
Various Envoy firmware behave differently, this makes the ability to capture probe request replies over a reload or initial startup an appreciated feature to assist with troubleshooting.
This PR:
- Adds the firmware version to the envoy.authenticate debug statement  
```
DEBUG:pyenphase.envoy:FW: 7.6.175, Authenticating to Envoy using token authentication
```
- Writes for each request made by envoy._request the request response url, request status, content-type and content …
> feat: write request reply to debuglog when in debug

- src/pyenphase/models/envoy.py
- src/pyenphase/models/meters.py
- tests/__snapshots__/test_endpoints.ambr
- tests/test_endpoints.py
Envoy Metered with consumption Current Transformers (CT) implemented report CT details in /ivp/meters/readings. For the consumption CT configured in `Solar with Load` this provides information on net-production (grid export) and net-consumption (grid-import). Net-consumption is also reported in /production as an increasing/decreasing total of import and export, CT readings however provides these as 2 increasing properties. [^1]
[^1]: variations between firmware release may exist.
This PR is step 1 of 3 to implement #69. It adds the meters model and Envoy data structures to store the CT data as well as tests for these. In addition to energy delivered and received it collects `active power`, `frequency`, `voltage`, `Current`, `power factor`, `State`, `measurement type`, `metering status` …
> refactor: Add CT meters model datastructures

- src/pyenphase/envoy.py
- tests/test_endpoints.py
Envoy_Model property provides a description of the Model, installed CT and phases as a string 
Tests added to test the Envoy_Model property, firmware and serial_number
> feat: add envoy_model property

- src/pyenphase/models/common.py
- src/pyenphase/models/envoy.py
- src/pyenphase/models/meters.py
- src/pyenphase/updaters/meters.py
- tests/__snapshots__/test_endpoints.ambr
First step to implement battery storage CT for use with HA Energy dashboard.
This PR creates the empty data structures needed to collect the storage CT data from /ivp/meters and ivp/meters/readings. The data itself is not yet included. The structures are the same as for the production and consumption CT. Some refactoring done to abandon the assumption no more as 2 CT types can report.
Test snapshot updated for the empty data structures added.
A next PR will add data collection and documentation update.
> refactor: add empty data structures for storage CT

- src/pyenphase/const.py
- src/pyenphase/envoy.py
- src/pyenphase/firmware.py
- tests/test_retries.py
When Envoy becomes unreachable (All connection attempts failed) the requests retry for-ever and setup, probe and update methods never return.
This pr re-configures the tenacity retry decorator to use a stop condition for maximum time since first request attempt.
- add max_request_delay parameter to Envoy and Firmware setups so time-out can be specified by caller
- Add MAX_REQUEST_DELAY with value 50 to const.py as default value
- Catch RetryError exception and return as EnvoyCommunicationError for Firmware, probe and update methods
The retry decorator has been replaced by a construct that allows using the max_request_delay. This can probably be done in a more python way. MyPy didn't like it either, hence the use of if not TYPE_CHECKING. It seemed the only option for a configurable value, …
> fix: endless loop on envoy unreachable

- .readthedocs.yml
ReadTheDocs errors in the build process. (https://github.com/pyenphase/pyenphase/issues/147)
```txt
ModuleNotFoundError: No module named 'myst_parser'
```
The log shows it's installing the myst parser. This is just running the build in a virtual environment to see if that solves the issue.
> docs: let readthedocs use virtualenv for build

- .readthedocs.yml
ReadTheDocs changed way to specify virtual environments recently. Using new format to see if it resolves the build failures, see  #147.
> docs: use new format to specify virtual env for readthedocs

- src/pyenphase/envoy.py
Httpx  is signalling deprecation warning 
```txt
/home/arie/dev/pyenphase/.venv/lib/python3.12/site-packages/httpx/_content.py:202: DeprecationWarning: Use 'content=<...>' to upload raw bytes/text content.
warnings.warn(message, DeprecationWarning)
```
triggered by https://github.com/pyenphase/pyenphase/blob/main/src/pyenphase/envoy.py#L242.
change to  `content=orjson.dumps(data)`
Mentioned in https://www.python-httpx.org/compatibility/#request-content
Needs testing with Envoy as my plain vanilla one doesn't allow any puts.
> chore(deps): replace deprecated httpx data with content

- src/pyenphase/envoy.py
- tests/test_auth.py
Httpx is signalling deprecation warning
```txt
/home/arie/dev/pyenphase/.venv/lib/python3.12/site-packages/httpx/_client.py:1559: DeprecationWarning: Setting per-request cookies=<...> is being deprecated, because the expected behavior on cookie persistence is ambiguous. Set cookies directly on the client instance instead.
warnings.warn(message, DeprecationWarning)
```
Described here: https://www.python-httpx.org/compatibility/ under header cookies.
Removed `cookies=` from get and put requests. Same cookies are in client received during jwt.
Added retrieval of cookies to test_auth to sustain cov.
Needs testing with Envoy for put. Get tested on my plain vanilla Envoy.
> chore(deps): remove deprecated cookies on request

- src/pyenphase/envoy.py
- src/pyenphase/exceptions.py
- tests/test_pre_v7_endpoints.py
When Envoy running FW 3.x restart they may send all zero values with status 200 while the internals are still restoring data. Observations are there may be 2-3 minutes of zero's before the pre-restart values are restored. When using the data with Home Assistant Energy dashboard the effect is a step in production values. See #168 and https://github.com/home-assistant/core/issues/120091.
This PR adds a _validate_data step to the envoy.update method to implement a data validation step. It currently implements 1 validation rule. If major firmware version is 3 and all values in data.system_production are zero it will signal exception `EnvoyPoorDataQuality`. For Home Assistant this will continue the outage until data is restored and only have a data gap instead of  gap followed by zero values. …
> fix: for fw 3.x mark production with only zero values as EnvoyPoorDataQuality error

- docs/model_autodoc.md
- src/pyenphase/firmware.py
This pr will refactor the [firmware class documentation.](https://pyenphase.readthedocs.io/en/latest/model_autodoc.html#pyenphase.firmware.EnvoyFirmware)
No code changes, only Docstrings or comments added or changed in python code, along with needed markdown file changes.
> docs: refactor firmware class documentation using docstrings

- docs/documenting.md
This pr augments the [documentation guidelines](https://pyenphase.readthedocs.io/en/latest/documenting.html) how to best use doctrings,
No code changes, only markdown file changes.
> docs: update guidelines to documentation for using docstring

- docs/model_autodoc.md
- src/pyenphase/ssl.py
This pr will refactor the [ssl helper documentation.](https://pyenphase.readthedocs.io/en/latest/model_autodoc.html#module-pyenphase.ssl)
No code changes, only Docstrings or comments added or changed in python code, along with needed markdown file changes.
> docs: refactor ssl helper documentation using docstring

- docs/model_autodoc.md
- src/pyenphase/json.py
This pr will refactor the [json helper documentation.](https://pyenphase.readthedocs.io/en/latest/model_autodoc.html#json)
No code changes, only Docstrings or comments added or changed in python code, along with needed markdown file changes.
> docs: refactor json helper documentation using docstrings

- src/pyenphase/const.py
This pr will refactor const.py for [SupportedFeatures](https://pyenphase.readthedocs.io/en/latest/model_autodoc.html#pyenphase.const.SupportedFeatures) and [PhaseNames](https://pyenphase.readthedocs.io/en/latest/model_autodoc.html#pyenphase.const.PhaseNames) documentation.
No code changes, only Docstrings or comments added or changed in python code, along with needed markdown file changes.
> docs: refactor const.py to use docstring for documentation.

- src/pyenphase/models/tariff.py
- tests/test_endpoints.py
Some Envoy return null in Tariff - storage_settings - mode. This causes an _"None is not a valid EnvoyStorageMode"_ exception. The issue is reported as an [HA issue](https://github.com/home-assistant/core/issues/135570#top) . Example debug log is provided with the tariff reply included.
This PR changes the  EnvoyStorageSettings.from_Api method to set mode to None if null is in the raw json.
```json
{
"tariff": {
"currency": {
"code": "AUD"
},
"logger": "mylogger",
"date": "1731383190",
"storage_settings": {
"mode": null,
"operation_mode_sub_type": null,
"reserved_soc": 0.0,
"very_low_soc": 10,
"charge_from_grid": false,
"date": "1731383190"
},
"single_rate": {
"rate": 0.2827,
"sell": 0.07
},
"seasons": [],
"seasons_sell": []
},
```
> fix: set EnvoyStorageMode to None if tariff storage_settings mode is null and causes exception None is not a valid EnvoyStorageMode.

- src/pyenphase/envoy.py
- tests/test_endpoints.py
The envoy.request method provides a method to issue request to the Envoy. It currently does not offer an option to specify the http method like _request does. When data is specified it only allows for the POST method.
This PR adds a method parameter, defaulting to None, which is passed on to the called _request method so users can opt to use any desired method by specifying it. The default behavior of using POST with data is unchanged.
> feat: Add http method to request method parameters

- .github/dependabot.yml
- poetry.lock
dependabot is failing so lets do this manually one by one
> chore: update zeroconf in the lock to speed up CI

- docs/documenting.md
Update [coding for documentation](https://pyenphase.readthedocs.io/en/stable/documenting.html) section of Docs to reflect the new Ruff formatting rules (D213).
> docs: update docstring examples to reflect ruff formatting rules.

- README.md
As we switched from black et al to ruff, let's replace the black badge with ruff badge in readme as well.
> docs: replace black badge by ruff badge in readme
